# Generated by Django 3.0 on 2020-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200411_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d'),
        ),
    ]
