# Generated by Django 3.0 on 2020-04-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_newletteremail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewletterEmail',
            new_name='NewsletterEmail',
        ),
    ]
