# Generated by Django 3.0 on 2020-05-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200430_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
