# Generated by Django 2.2 on 2019-04-29 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_topic', models.CharField(max_length=255)),
                ('course_price', models.FloatField()),
                ('course_title', models.CharField(max_length=255)),
                ('course_outline', models.TextField()),
                ('course_requirements', models.TextField()),
                ('course_description', models.TextField()),
                ('target_students', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=254)),
                ('nationality', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('is_student', models.BooleanField(default=True)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_promoter', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='WishListCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Course')),
                ('wish_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_course', to='accounts.WishList')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_list', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Course')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_course', to='accounts.PurchaseList')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilename', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('payment_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_info', to='accounts.PaymentInfo')),
            ],
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='accounts.Profile'),
        ),
        migrations.CreateModel(
            name='InstructorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_revenue', models.FloatField(blank=True, max_length=200)),
                ('number_of_students', models.IntegerField(blank=True)),
                ('rating', models.FloatField(blank=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCoursesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lists', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorBankingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=455)),
                ('banking_info', models.CharField(max_length=455)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_info', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('None', 'None'), ('D', 'Diploma'), ('B', "Bachelor's Degree"), ('M', "Master's Degree"), ('PH', 'PhD')], default='None', max_length=2)),
                ('major', models.CharField(max_length=344)),
                ('experience', models.TextField(help_text='Briefly, describe your background knowledge related to the topics you want to teach')),
                ('status', models.CharField(choices=[('None', 'None'), ('submitted', 'Submitted'), ('processed', 'Decision has been made')], default='None', max_length=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_qualification', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('card_number', models.IntegerField()),
                ('expriy_date', models.DateField()),
                ('security_number', models.IntegerField()),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_info', to='accounts.PaymentInfo')),
            ],
        ),
    ]
