# Generated by Django 2.2 on 2019-06-17 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='wishlistcourse',
            name='wish_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.WishList'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='purchaselist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_list', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='purchase_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_course', to='accounts.PurchaseList'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='payment_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_info', to='accounts.PaymentInfo'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='instructorresume',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_qualification', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='instructorreport',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='instructorcourseslist',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lists', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='instructorbankinginfo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_info', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='cardpaymentinfo',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_info', to='accounts.PaymentInfo'),
        ),
    ]
