# Generated by Django 2.2 on 2019-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorreport',
            name='instructor_revenue',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
