# Generated by Django 2.2 on 2019-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190426_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('submitted', 'Submitted'), ('processed', 'Decision has been made')], default='None', max_length=2),
        ),
    ]
