# Generated by Django 2.2 on 2019-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190529_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorresume',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instructor_application_status',
            field=models.CharField(choices=[('none', 'None'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
