# Generated by Django 2.2 on 2019-05-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190529_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorresume',
            name='degree',
            field=models.CharField(choices=[('None', 'None'), ('D', 'Diploma'), ('B', "Bachelor's Degree"), ('M', "Master's Degree"), ('PH', 'PhD')], max_length=2),
        ),
    ]
