# Generated by Django 2.2 on 2019-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190530_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorresume',
            name='degree',
            field=models.CharField(choices=[('D', 'Diploma'), ('B', "Bachelor's Degree"), ('M', "Master's Degree"), ('PH', 'PhD')], max_length=2),
        ),
    ]
