# Generated by Django 2.2 on 2019-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190530_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorreport',
            name='rates',
            field=models.IntegerField(null=True),
        ),
    ]
