# Generated by Django 3.0 on 2020-04-20 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Name of the Course')),
                ('course_topic', models.CharField(max_length=255)),
                ('course_price', models.FloatField(null=True)),
                ('course_title', models.CharField(max_length=255)),
                ('course_outline', models.TextField()),
                ('course_requirements', models.TextField()),
                ('course_level', models.CharField(choices=[('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced')], default='None', max_length=3)),
                ('course_outcomes', models.TextField()),
                ('course_description', models.TextField()),
                ('target_students', models.TextField()),
                ('course_picture', models.ImageField(null=True, upload_to='courses/%Y/%m/%d')),
                ('course_subcategory', models.CharField(choices=[('0', 'Web Development'), ('1', 'Calculus I'), ('2', 'Programming'), ('none', 'None')], default='None', max_length=6)),
                ('course_type', models.CharField(choices=[('none', 'None'), ('academic', 'Academic Learning'), ('practical', 'Practical Learning'), ('tech', 'Tech-Related Courses'), ('theory', 'Theoretical Learning')], default='None', max_length=25)),
                ('course_rating', models.FloatField(null=True)),
                ('course_length', models.FloatField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discounted', models.BooleanField(default=False)),
                ('course_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.IntegerField(null=True)),
                ('section_name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('num_visitors', models.IntegerField(default=0)),
                ('num_buyers', models.IntegerField(default=0)),
                ('course_revenue', models.FloatField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('file', 'File')], default='None', max_length=10)),
                ('file', models.FileField(upload_to='courses/contents/%Y/%m/%d')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.CourseSection')),
            ],
        ),
    ]
