# Generated by Django 2.2 on 2019-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='section_num',
            field=models.IntegerField(null=True),
        ),
    ]
