# Generated by Django 2.2 on 2019-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_picture',
            field=models.ImageField(null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
