# Generated by Django 2.2 on 2019-06-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190615_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereport',
            old_name='course_rating',
            new_name='rating',
        ),
    ]
