# Generated by Django 2.2 on 2019-04-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190429_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_picture',
            field=models.ImageField(null=True, upload_to='courses/%Y/%m/%d'),
        ),
    ]
