# Generated by Django 2.2 on 2019-07-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190701_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='course_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='courses.CourseReport'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='courses.Order'),
        ),
    ]
