# Generated by Django 2.2 on 2019-06-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190615_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereport',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
