# Generated by Django 2.2 on 2019-06-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190615_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereport',
            name='course_revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coursereport',
            name='num_buyers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coursereport',
            name='num_visitors',
            field=models.IntegerField(null=True),
        ),
    ]
