# Generated by Django 2.2 on 2019-05-14 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190429_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('file', 'File')], default='None', max_length=10)),
                ('file', models.FileField(upload_to='courses/contents/%Y/%m/%d')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.CourseSection')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.RemoveField(
            model_name='file',
            name='course_section',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
        migrations.RemoveField(
            model_name='image',
            name='course_section',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course_section',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
