# Generated by Django 2.1.2 on 2019-03-31 06:48

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('InstructorEmail', models.EmailField(max_length=255, unique=True)),
                ('BirthDate', models.DateField()),
                ('PhoneNumber', phone_field.models.PhoneField(max_length=31)),
                ('Country', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('UserStatus', models.BooleanField(default=False, verbose_name='user_status')),
                ('InstructorStatus', models.BooleanField(default=False, verbose_name='instructor status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CoursesList', to='InstructorAuthentication.Instructor')),
            ],
        ),
    ]
