# Generated by Django 2.1.4 on 2019-02-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduControl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='LastName',
        ),
    ]
