# Generated by Django 2.1.4 on 2019-02-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduControl', '0002_auto_20190206_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
